[package]
name = "tenboard"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.5.0"
rand = "0.8.5"
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0"
serde_repr = "0.1"
